# Generated by Django 4.2.5 on 2024-08-06 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0002_rename_label_sprint_name_remove_sprint_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
